//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8937
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IUpdateOrders", Namespace="http://tempuri.org/")]
public partial class UpdateOrders : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback UpdateOperationCompleted;
    
    /// <remarks/>
    public UpdateOrders() {
        this.Url = "http://localhost:49704/UpdateOrders.svc";
    }
    
    /// <remarks/>
    public event UpdateCompletedEventHandler UpdateCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUpdateOrders/Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public ResponseInfo Update([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string authPartnerCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string payeeCodes) {
        object[] results = this.Invoke("Update", new object[] {
                    userName,
                    password,
                    authPartnerCode,
                    payeeCodes});
        return ((ResponseInfo)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdate(string userName, string password, string authPartnerCode, string payeeCodes, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Update", new object[] {
                    userName,
                    password,
                    authPartnerCode,
                    payeeCodes}, callback, asyncState);
    }
    
    /// <remarks/>
    public ResponseInfo EndUpdate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ResponseInfo)(results[0]));
    }
    
    /// <remarks/>
    public void UpdateAsync(string userName, string password, string authPartnerCode, string payeeCodes) {
        this.UpdateAsync(userName, password, authPartnerCode, payeeCodes, null);
    }
    
    /// <remarks/>
    public void UpdateAsync(string userName, string password, string authPartnerCode, string payeeCodes, object userState) {
        if ((this.UpdateOperationCompleted == null)) {
            this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
        }
        this.InvokeAsync("Update", new object[] {
                    userName,
                    password,
                    authPartnerCode,
                    payeeCodes}, this.UpdateOperationCompleted, userState);
    }
    
    private void OnUpdateOperationCompleted(object arg) {
        if ((this.UpdateCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PontualMoneyTransfer.Services.Service.Dat" +
    "aContract")]
public partial class ResponseInfo {
    
    private int errorCodeField;
    
    private bool errorCodeFieldSpecified;
    
    private string errorMessageField;
    
    private string quotationField;
    
    private byte[] receiptBytesField;
    
    private bool successField;
    
    private bool successFieldSpecified;
    
    /// <remarks/>
    public int ErrorCode {
        get {
            return this.errorCodeField;
        }
        set {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ErrorCodeSpecified {
        get {
            return this.errorCodeFieldSpecified;
        }
        set {
            this.errorCodeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Quotation {
        get {
            return this.quotationField;
        }
        set {
            this.quotationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
    public byte[] ReceiptBytes {
        get {
            return this.receiptBytesField;
        }
        set {
            this.receiptBytesField = value;
        }
    }
    
    /// <remarks/>
    public bool Success {
        get {
            return this.successField;
        }
        set {
            this.successField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SuccessSpecified {
        get {
            return this.successFieldSpecified;
        }
        set {
            this.successFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ResponseInfo Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ResponseInfo)(this.results[0]));
        }
    }
}
